# -*- coding: utf-8 -*-
"""Placement_LogisticRegression_demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bnbjShlglHLX1krzdQarzQI9lJs6IYwp
"""

df=pd.read_csv('/content/Job_Placement_Data.csv')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from mlxtend.plotting import plot_decision_regions
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

df.head()

df['status_1'] = df['status'].apply(lambda x: 1 if x == 'Placed' else 0)
plt.scatter(df['degree_percentage'],df['mba_percent'],c=df['status_1'])

X = df.iloc[:, [6, 11]]
y = df.iloc[:,-1]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

clf=LogisticRegression()

clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

accuracy_score(y_pred,y_test)

plot_decision_regions(X_train, y_train.values, clf=clf, legend=2)